import React from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, TextInputProps, View } from "react-native";
import { theme } from "@/theme/theme";
export function Button({ title, onPress, loading, disabled }: { title: string; onPress?: () => void; loading?: boolean; disabled?: boolean }) { return <Pressable accessibilityRole="button" disabled={disabled || loading} onPress={onPress} style={[styles.button, (disabled || loading) && styles.disabled]}>{loading ? <ActivityIndicator color="#fff" /> : <Text style={styles.buttonText}>{title}</Text>}</Pressable>; }
export function Input(props: TextInputProps) { return <TextInput placeholderTextColor={theme.colors.muted} autoCapitalize="none" style={styles.input} {...props} />; }
export function Card({ children }: { children: React.ReactNode }) { return <View style={styles.card}>{children}</View>; }
export function LoadingState({ label = "Caricamento in corso…" }) { return <View style={styles.center}><ActivityIndicator /><Text style={styles.muted}>{label}</Text></View>; }
export function EmptyState({ title, message }: { title: string; message: string }) { return <Card><Text style={styles.title}>{title}</Text><Text style={styles.muted}>{message}</Text></Card>; }
export const styles = StyleSheet.create({ center: { flex: 1, alignItems: "center", justifyContent: "center", gap: 12, padding: 24 }, card: { backgroundColor: theme.colors.surface, borderColor: theme.colors.border, borderWidth: 1, borderRadius: theme.radius.lg, padding: theme.spacing.lg, gap: theme.spacing.md }, title: { fontSize: 24, fontWeight: "700", color: theme.colors.text }, muted: { color: theme.colors.muted }, input: { backgroundColor: "#fff", borderColor: theme.colors.border, borderWidth: 1, borderRadius: theme.radius.md, padding: 14, fontSize: 16 }, button: { alignItems: "center", backgroundColor: theme.colors.primary, borderRadius: theme.radius.md, padding: 14 }, disabled: { opacity: 0.6 }, buttonText: { color: "#fff", fontWeight: "700" } });
